### ISSUE TITLE
Simpler UpdateTo?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Data.Adaptive#49]
It feels like `clist.UpdateTo` could also have a simpler overload so for primitive values we can just call
```
            amodel.SKPoints.UpdateTo(model.SKPoints)
```

Separately, I  wonder if ChangeableValue should have an `UpdateTo` for symmetry, perhaps where
```fsharp
            amodel.RefreshViewIsRefreshing.UpdateTo(model.RefreshViewIsRefreshing)
```
is equal to 
```fsharp
            if model.RefreshViewIsRefreshing <> amodel.RefreshViewIsRefreshing.Value then 
                amodel.RefreshViewIsRefreshing.Value <- model.RefreshViewIsRefreshing
```
and with the more sophisticated overload available too

**Comment by krauthaufen** [comment]
Hey, generally speaking the `UpdateTo` members taking `init` and `update` on cmap/clist are not really optimal since they need to visit all entries in the list/map and call at least `update`. 

For model-diffing i added `ChangeableModelMap` and `ChangeableModelList` respectively, which perform a little better, when applicable (cmap.UpdateTo may provide some additional value)

However I just added simpler `UpdateTo` members to `cset`, `cmap`, `clist` and `cval` respectively...

Note that they internally use `cheapEquals` (and not real equality) to guard the delta-computation.
The only exception here is `cval` since the equality check is the only thing guarding the marking (as opposed to sets/maps/lists where deltas may still get empty when not cheap-equals)

**Comment by dsyme** [comment]
Interesting, thank you!

**Comment by krauthaufen** [comment]
Btw I had to add Reflection.Emit for the cheap-equality, which works on nearly all platform afaik.

Just let me know if that causes any problems (thinking about iOS), but sadly I couldn't figure out a way of implementing ShallowEquals efficiently for structs holding reference types.

**Comment by dsyme** [comment]
> Just let me know if that causes any problems (thinking about iOS), but sadly I couldn't figure out a way of implementing ShallowEquals efficiently for structs holding reference types.

Yes, that's correct.  I was always loathe to add code emit to FSharp.Core but it's reasonable in a derived library like this

**Comment by dsyme** [comment]
I'll close this since you've addressed it, thanks!
