### ISSUE TITLE
foldGroup / reduction should return the seed if empty

### ISSUE THREAD

**Issue by luithefirst** [fsprojects/FSharp.Data.Adaptive#68]
A reduction should return the seed if there are no elements. Currently, when using floating-point numbers and providing a subtract function this is not given due to limitation of their arithmetic. Implementing a special condition to guarantee this should be possible?

This would be a unit test:
```
var r = new Random(1);
var list = new ChangeableIndexList<double>();
for (int i = 0; i < 10000; i++)
    list.Add(r.NextDouble() * 1111);

var sum = list.Sum();
Report.Line("Sum: {0}", sum.GetValue()); // 5.5e6

using (Adaptive.Transact)
    list.Clear();

Report.Line("Sum: {0}", sum.GetValue()); // currently: 2.7e-8
```

**Comment by krauthaufen** [comment]
Hey, certainly this is a bit odd, but on the other hand the floating point subtraction is not precisely inverse to the addition. Furthermore floating point addition is not even associative, so the entire reduction will not yield the identical results as a classic fold. That said I get your point, but isn't the empty-case just the one case where the internal error of the operation gets visible? We could certainly have a special case for empty, but the same error will still exist on singletons, pairs, etc. 
I guess my point is that in the end we would need special cases for 0, 1 and 2 since these cases have a "precise" result regardless of non-associativity...

**Comment by luithefirst** [comment]
Right, also the case with only 1 element could be handled better, this would also be nice. I'm aware of the precision issues and in my application, this has not been an issue so far, except in the empty case where it gets really messy. I usually clamp the result to the initial value or even check if the value is within epsilon of the initial value as it otherwise would result in broken behavior. Having a deterministic result in the empty case would make this code obsolete :)

**Comment by krauthaufen** [comment]
Hey, after thinkig about that for a while it basically boils down to this:

1. Whenever empty return the seed
2.Whenever single return `add(seed,element)` (maybe just the element itself could also be viable here)
3. Whenever the delta count is larger or equal to the new content count recompute the result from scratch (this maybe also covers the other cases... Need to think about that)
