### ISSUE TITLE
FSharp.Data.Adaptive and Xamarin.iOS

### ISSUE THREAD

**Issue by Liminiens** [fsprojects/FSharp.Data.Adaptive#70]
Hi!

Currently `ShallowEqualityComparer` uses `Reflection.Emit`, which is not allowed on iOS due to code generation limitations. Maybe there is a way to provide an iOS version without `DynamicMethod` somehow?

**Comment by krauthaufen** [comment]
Hey, I suspected that this would happen eventually and there is a simple workaround by just returning false in the shallowequals on iOS, but I currently don't know how to do that properly. Should wr explicitly include an iOS build that doesn't depend on the reflection.emit package?

This "hack" would change the behaviour a little in some places (a few needless re-executions) but i think it would be acceptable for the moment.

**Comment by krauthaufen** [comment]
Okay cool, so we would just need a way to figure out whether or not it's running on iOS...

Maybe we could just `try ... with` some reflection.emit thing once to figure out if it works.
Please let me know if we can reference it without breaking anything, but I agree that it looks that way since the [package](https://www.nuget.org/packages/System.Reflection.Emit.Lightweight/) itself explicitly has a platform `Xamarin.iOS 1.0`

**Comment by krauthaufen** [comment]
Hey,
I'm just pushing version `0.0.26` to nuget which avoids DynamicMethods when they don't work (using this exception test).

Could you test this version on iOS (since I don't have an iPhone/iPad/Emulator)

**Comment by krauthaufen** [comment]
With a little help we were able to test that, so Adaptive now works properly on Xamarin.IOS

**Comment by Liminiens** [comment]
Thank you!
