### ISSUE TITLE
Computation graph serialization

### ISSUE THREAD

**Issue by klimovgv** [fsprojects/FSharp.Data.Adaptive#73]
I'm working on a project involving complex financial models calculations.
Each function we have is implemented as an azure cloud function and wrapped in an adaptive-value (inside we issue an HTTP request to get the actual result).
Result graph is rather large, and we want to have an ability to persist/restore it (along with the incoming/outgoing values).
How do you think, is this a viable approach, and if so, is there any way to serialize/restore state of an adative-graph?

PS Great library, very powerful and expressive!

**Comment by krauthaufen** [comment]
Hey, that's definetly a cool way of using adaptive. Unfortunately all our `avals` currently do not track their input-cells explicitly (however most of them could actually do that quite easily). The main problem i see here is that `bind`/`collect` values/lists have a dynamic dependency graph, so serializing them would require the system to remain unmodified while serializing it.

That said, I think serializing these graphs would be quite cool, since they could also be used for visualization, etc.

**Comment by krauthaufen** [comment]
Closing this, since tracking inputs in adaptive would be very tedious and no-one has time for doing it currently...
